apiVersion: v1
kind: Service
metadata:
  name: local-devops-app-service
spec:
  type: LoadBalancer # Dışarıdan erişilebilir olması için
  selector:
    app: local-devops-app # Deployment'taki etiketle eşleşmeli
  ports:
    - protocol: TCP
      port: 80      # Dışarıdan 80 portuna geleceğiz (HTTP standart)
      targetPort: 8080 # İçerideki 8080 portuna yönlenecek