name: Docker Image CI

# Bu pipeline ne zaman çalışsın?
# main branch'ine kod pushlandığında tetiklen.
on:
  push:
    branches: [ "main" ]

# Global değişkenler
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # GitHub Token'ına paket yazma izni veriyoruz
    permissions:
      contents: read
      packages: write

    steps:
      # 1. GitHub'daki kodunu sanal makineye çek
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. GitHub Container Registry'e (GHCR) giriş yap
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. İmaj ismini ve etiketlerini ayarla (Küçük harfe çevirme işlemi)
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      # 4. Docker imajını build et ve GHCR'a gönder (Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./LocalDevOpsApp
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}